docs: enable i18n
nation3/wiki pull request #11
Opened 2022-05-10 06:48 UTC by aahna-ashina

- [x] Add Chinese locale: `zh`
- [ ] Translate docs from English to Chinese

<img width="366" alt="Screen Shot 2022-05-10 at 2 37 16 PM" src="https://user-images.githubusercontent.com/95955389/167565468-0cc3142c-ad18-4fcc-9b6c-5209583741f4.png">

2022-05-10 08:41 UTC, aahna-ashina commented
@anastasiyabelyaeva @zhizhi1993 Please review the changes under the "Files changed" tab: https://github.com/nation3/wiki/pull/11/files

2022-05-11 01:24 UTC, aahna-ashina commented
Chinese Markdown docs:
```
i18n/zh/docusaurus-plugin-content-docs/current
├── Cloud Nations Ecosystem
│   ├── cities.md
│   ├── cloud-countries.md
│   ├── healthcare.md
│   ├── internet-communities.md
│   ├── jurisdictional-competition.md
│   ├── sez.md
│   └── tools-communities.md
├── DAO
│   ├── audits.md
│   ├── governance.md
│   └── token-ecosystem.md
├── ecosystem.md
├── intro.md
└── reads.md
```

2022-05-11 01:42 UTC, Mosquitochen commented
[Nation3_Wiki_CN_V3.zip](https://github.com/nation3/wiki/files/8666001/Nation3_Wiki_CN_V3.zip)

2022-05-11 03:36 UTC, Zhaogw requested changes

2022-05-11 03:36 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/reads.md
> +*   [如何启动一个新的国家](https://1729.com/how-to-start-a-new-country/ "如何启动一个新的国家")：很好地概述了在互联网上启动一个云第一、地最后的国家的多种机制。
[如何建立一个新的国家](https://1729.com/how-to-start-a-new-country/ "如何建立一个新的国家")：很好地概述了在互联网上建立由云端到陆地的国家的多种机制。

2022-05-11 03:36 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/cities.md
> +基本上是为提高生活质量和增加归属感而建造的新城市和社区。
为提高生活质量和增加归属感而实质建造的新城市和社区。

2022-05-11 03:36 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/cities.md
> +*   [CityDAO：](https://www.citydao.io/ "CityDAO：")在美国区块链友好的怀俄明州创建一个加密货币支持的城市。以DAO的形式组织起来。
用DAO的形式在美国对区块链持友好态度的怀俄明州创建一个使用加密货币的城市。

2022-05-11 03:36 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/cloud-countries.md
> +**云国度**是提供或旨在提供类似于民族国家的服务的社区。但是，他们不是以土地起家，而是在互联网上建立服务和积累社区，目的是最终扩展到物理领域。
**云国度**是提供或旨在提供类似于民族国家服务的社区。但是，他们不是从土地开始，而是在互联网上建立服务和积累社区，目的是最终扩展到现实世界。

2022-05-11 03:36 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/internet-communities.md
> +一些互联网社区旨在超越传统界限，为其参与者提供意义和归属。历史上，人类从属于一个宗教团体、一个民族国家甚至体育俱乐部中获得意义。
一些互联网社区旨在超越传统界限，为参与者提供意义和归属感。 从历史上看，人类从一个宗教团体、一个民族国家甚至是体育俱乐部中获得人生意义。

2022-05-11 03:36 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/tools-communities.md
> +使这些互联网社区和云第一的民族国家能够以远程、分散的方式有效开展工作的工具。
使这些互联网社区和云端的民族国家能够以远程、分散的方式有效开展工作的工具。

2022-05-11 03:46 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/cities.md
> +基本上是为提高生活质量和增加归属感而建造的新城市和社区。
为提高生活质量和增加归属感而实质建造的新城市和社区

2022-05-11 03:46 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/cities.md
> +*   [CityDAO：](https://www.citydao.io/ "CityDAO：")在美国区块链友好的怀俄明州创建一个加密货币支持的城市。以DAO的形式组织起来。
[CityDAO：](https://www.citydao.io/ "CityDAO：")用DAO的形式在美国对区块链友好的怀俄明州创建一个支持加密货币的城市。

2022-05-11 03:46 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/cloud-countries.md
> +**云国度**是提供或旨在提供类似于民族国家的服务的社区。但是，他们不是以土地起家，而是在互联网上建立服务和积累社区，目的是最终扩展到物理领域。
**云国度**是提供或旨在提供类似于民族国家服务的社区。但是，他们不是从土地开始，而是在互联网上建立服务和积累社区，目的是最终扩展到现实领域。

2022-05-11 03:46 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/internet-communities.md
> +一些互联网社区旨在超越传统界限，为其参与者提供意义和归属。历史上，人类从属于一个宗教团体、一个民族国家甚至体育俱乐部中获得意义。
一些互联网社区旨在超越传统界限，为其参与者提供意义和归属感。历史上，人类从一个宗教团体、一个民族国家甚至体育俱乐部中获得人生意义。

2022-05-11 03:46 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/Cloud Nations Ecosystem/tools-communities.md
> +使这些互联网社区和云第一的民族国家能够以远程、分散的方式有效开展工作的工具。
使这些互联网社区和云端的民族国家能够以远程、分散的方式有效开展工作的工具。

2022-05-11 03:46 UTC, Zhaogw commented on i18n/zh/docusaurus-plugin-content-docs/current/reads.md
> +*   [如何启动一个新的国家](https://1729.com/how-to-start-a-new-country/ "如何启动一个新的国家")：很好地概述了在互联网上启动一个云第一、地最后的国家的多种机制。
[如何建立一个新的国家](https://1729.com/how-to-start-a-new-country/ "如何建立一个新的国家")：很好地概述了在互联网上启动一个由云端到陆地的国家的多种机制。

2022-05-11 05:38 UTC, aahna-ashina commented
<img width="1280" alt="Screen Shot 2022-05-11 at 1 37 46 PM" src="https://user-images.githubusercontent.com/95955389/167776463-dc3167eb-3e2f-4cc3-9dfc-dd42768b3fbd.png">

2022-05-11 06:20 UTC, aahna-ashina commented
<img width="1280" alt="Screen Shot 2022-05-11 at 2 17 26 PM" src="https://user-images.githubusercontent.com/95955389/167781801-0e7e080f-a0d9-4e4d-9b2d-8a744699cc9a.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 17 36 PM" src="https://user-images.githubusercontent.com/95955389/167781805-6df47f38-042a-46a6-be16-870264641665.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 17 43 PM" src="https://user-images.githubusercontent.com/95955389/167781809-4b3819c0-af43-431a-8a3f-7bd0a0054128.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 17 50 PM" src="https://user-images.githubusercontent.com/95955389/167781811-19951e4a-a787-4e66-8c29-90dda30dc4b8.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 17 55 PM" src="https://user-images.githubusercontent.com/95955389/167781813-81546b99-8971-4dcc-9124-35a70af14777.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 01 PM" src="https://user-images.githubusercontent.com/95955389/167781817-23ef22b2-bef8-48fd-aa6b-d5a17bffeb63.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 06 PM" src="https://user-images.githubusercontent.com/95955389/167781819-c6bb1e37-f879-4e8c-a5b1-3bb1dff25b0a.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 11 PM" src="https://user-images.githubusercontent.com/95955389/167781823-cadf0b1b-8f7a-4681-a1a1-8f7c462c86c4.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 16 PM" src="https://user-images.githubusercontent.com/95955389/167781825-55089b6d-7035-4483-97a1-f7f186625548.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 21 PM" src="https://user-images.githubusercontent.com/95955389/167781828-39b671cf-22cf-4f11-8854-3ae0bc0c4c0e.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 27 PM" src="https://user-images.githubusercontent.com/95955389/167781830-144f9d87-dfa7-4220-bcf3-3feffcf9a192.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 32 PM" src="https://user-images.githubusercontent.com/95955389/167781833-d8eaca72-1a36-4e28-a2cf-a7389f558e4a.png">

<img width="1280" alt="Screen Shot 2022-05-11 at 2 18 38 PM" src="https://user-images.githubusercontent.com/95955389/167781837-58aa98ef-6ca1-4d08-89ed-365b14f31bba.png">

2022-05-11 10:07 UTC, merged